name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: |
            # Optional: Add host fingerprints for safety (example shown below)
            ec2-your-ip.compute-1.amazonaws.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ...

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Virtual env
        run: |
          sudo apt install python3.12-venv -y
          python3 -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python3 -m unittest app.py

      # ------ REMOTE DEPLOYMENT STEPS VIA SSH-ACTION ------

      - name: SSH Pull latest code
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: fzansari              # or ubuntu, depending on your AMI
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/fzansari/flask-todo-app
            git pull origin main

      - name: SSH Install dependencies
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: fzansari
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/fzansari/flask-todo-app
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - name: SSH Restart app
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: fzansari
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/fzansari/flask-todo-app
            pkill -f "python3 app.py" || true
            python3 app.py 
            exit 0
